### ISSUE TITLE
ship inventory does not update while docked

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#4] opened 2019-06-11 21:17 UTC
**Describe the bug**
Any action that would update the ship inventory while docked does not appear until you undock and redock.  Refresh has no effect.

**To Reproduce**
Assemble, Trash or `.create` a ship while docked.

**Comment by THUNDERGROOVE** [comment] 2019-06-11 23:17
This is a duplicate of #3 so I'll close this as the other has more information.

Thanks!

**Closed as completed by THUNDERGROOVE** 2019-06-11 23:17 UTC
