### ISSUE TITLE
Can change fittings in space without a fitting service

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#76] opened 2019-12-03 03:27 UTC
Undock a Caracel, click Fitting.  You shouldn't be able to change modules unless you're next to a POS or Orca with a fitting service.

**Comment by zhyrohaad** [comment] 2019-12-03 17:08
while normally, this would be an error, it is not on this test server.
this allows changing fitting on-the-fly while testing.
i use it often to test diff modules in same scenario.

i am closing this as a non-issue....its working as intended.

**Closed as completed by zhyrohaad** 2019-12-03 17:08 UTC
